VLFeat - Documentation - C API
VLFeat.org
Documentation - C API
heap.h File Reference
Heap.
#include <stdlib.h>
#include "generic.h"
Data Structures
struct _VlHeap
Heap object.
Typedefs
typedef struct _VlHeap VlHeap
Heap object.
Functions
Creating and disposing
VL_EXPORT VlHeap * vl_heap_new (void *nodes, int nodeSize, int(*compare)(void const *a, void const *b))
Create new heap object.
VL_EXPORT void vl_heap_delete (VlHeap *self)
Delete heap object.
Manipulating nodes
VL_INLINE int unsigned vl_heap_get_node_num (VlHeap *self)
Get number of nodes in the heap.
VL_INLINE void * vl_heap_get_node_with_index (VlHeap *self, int unsigned nodeIndex)
Get node with given index.
VL_INLINE void vl_heap_clear (VlHeap *self)
Clear the heap.
VL_EXPORT void vl_heap_push (VlHeap *self)
Push a new node into the heap.
VL_EXPORT void * vl_heap_pop (VlHeap *self)
Pop the smallest node from the heap.
VL_EXPORT void vl_heap_update (VlHeap *self, int unsigned nodeIndex)
Update node priority.
Retrieving and setting paramters
VL_EXPORT void vl_heap_set_swap_func (VlHeap *self, void(*swap)(void *custom, void *a, void *b), void *customData)
Set function used to swap nodes.
Moving in the heap
For internal use only.
VL_INLINE int unsigned vl_heap_parent (int unsigned nodeIndex)
Get index of parent node.
VL_INLINE int unsigned vl_heap_left_child (int unsigned nodeIndex)
Get index of left child.
VL_INLINE int unsigned vl_heap_right_child (int unsigned nodeIndex)
Get index of right child.
Detailed Description
VlHeap implements a heap. The main use of a heap is to organize an array of objects (called nodes) in a priority queue.
Overview
Technical details
VlHeap behavior (node comparison and swapping functions) are set at run-time. This incurs in a small overhead, which in most cases is tolerable, but in thigt loops might be unacceptable. In such cases, heap-t.h can be used instead.
To create a VlHeap objet to mange an array of nodes call vl_heap_new specifying
the array nodes of nodes,
the size (in bytes) of each node,
a function compare specifying an order relation between nodes.
Notice that the number of nodes into the array is left unspecified. Initially, the heap is empty. Calling vl_heap_push includes into the heap the first node of the array nodes[0]. Further calls to vl_heap_push include successive nodes. Calling vl_heap_pop removes and returns the smallest node (as specified by compare) from the heap. vl_heap_clear empties the heap.
VlHeap rearranges the nodes in the heap to maintain the proper ordering of the queue (heap property). By default, this is done by copying the memory occupied by each node. For efficiency nodes should be small objects (consider using pointers).
VlHeap supports updaing node priorities. After changing the priority of a node (in the heap), call vl_heap_update to update the heap. Only one node can be changed at a time.
To use vl_heap_update one needs to know the index of the updated node in the heap array. Since nodes are rearranged by the heap operations, this is in general different from the index of the node when it was first added to the array. This problem may be solved by customizing the node swapping function (vl_heap_set_swap_func) to track the node indexes.
The heap is stored as a binary tree with the property (heap property) that any node is not larger than any of its children. In particular, the root is the smallest node.
VlHeap uses the standard binary tree representation as an array of nodes. node[0] corresponds to the root, node[1] and node[2] to the root left and right children and so on. In this way, the tree structure is fully specified by the total numeber of nodes.
Assuming that the heap has N nodes (from node[0] to node[N-1]), adding the node node[N] to the heap is done by a push down operation: if the node node[N] is smaller than its parent (violating the heap property) it is pushed down by swapping it with the parent, and so on recursively.
Removing the smallest element node[0] with an heap of N nodes is done by swapping node[0] with node[N-1]. If then node[0] is larger than any of its children, it is swapped with the smallest of the two and so on recursively (push up operation).
Author:
Andrea Vedaldi
Definition in file heap.h.
Function Documentation
void vl_heap_clear (VlHeap * self)
Parameters:
self heap object instance.
Definition at line 87 of file heap.h.
VL_EXPORT void vl_heap_delete (VlHeap * self)
Parameters:
self heap object to delete.
Definition at line 170 of file heap.c.
References vl_free().
int unsigned vl_heap_get_node_num (VlHeap * self)
Parameters:
self heap object instance.
Returns:
number of nodes in the heap.
Definition at line 76 of file heap.h.
void * vl_heap_get_node_with_index (VlHeap * self, int unsigned nodeIndex)
Parameters:
self heap object instance.
nodeIndex index of the heap node.
Returns:
pointer to the node.
Definition at line 63 of file heap.h.
Referenced by vl_heap_down(), vl_heap_pop(), and vl_heap_up().
VL_INLINE int unsigned vl_heap_left_child (int unsigned nodeIndex)
For internal use only.
Parameters:
nodeIndex a node index.
Returns:
index of the left child.
Definition at line 115 of file heap.h.
Referenced by vl_heap_right_child(), vl_heap_up(), and void().
VL_EXPORT VlHeap* vl_heap_new (void * nodes, int nodeSize, int(*)(void const *a, void const *b) compare)
Parameters:
nodes array of nodes.
nodeSize size in bytes of a node.
compare node comparison function.
Returns:
new heap object instance.
Definition at line 151 of file heap.c.
References vl_malloc().
VL_INLINE int unsigned vl_heap_parent (int unsigned nodeIndex)
For internal use only.
Parameters:
nodeIndex a node index.
Returns:
index of the parent node.
Definition at line 102 of file heap.h.
Referenced by vl_heap_down(), and void().
VL_EXPORT void* vl_heap_pop (VlHeap * self)
Parameters:
self heap object instance.
Returns:
pointer do extracted node (or NULL if the heap is empty).
The function removes the root node from the heap and moves it to the firs position after the heap end. It then returns a pointer to it.
Example
To extract smallest value from an heap of floats:
 float * node = vl_heap_pop (heap) ;
Definition at line 296 of file heap.c.
References vl_heap_get_node_with_index(), and vl_heap_up().
VL_EXPORT void vl_heap_push (VlHeap * self)
Parameters:
self heap object instance.
The function adds to the heap the first node after the heap end.
Example
To add a node of value 1.0 to an heap of floats:
 float * node = vl_heap_get_node_with_index (heap, vl_heap_get_node_num (heap)) ;
 *node = 1.0F ;
 vl_heap_push (self) ;
Definition at line 272 of file heap.c.
References vl_heap_down().
VL_INLINE int unsigned vl_heap_right_child (int unsigned nodeIndex)
For internal use only.
Parameters:
nodeIndex a node index.
Returns:
index of the right child.
Definition at line 127 of file heap.h.
References vl_heap_left_child().
Referenced by vl_heap_up(), and void().
VL_EXPORT void vl_heap_set_swap_func (VlHeap * self, void(*)(void *custom, void *a, void *b) swap, void * customData)
Parameters:
self heap object instance.
swap swap function.
customData pointer to data passed to the swap function.
The swap function swap is called whenever nodes are rearranged in the heap. swap must swap the node pointed by a with the node pointed by b.
You can customize the swap function to track the index of the nodes as they are rearranged in the heap.
Definition at line 133 of file heap.c.
VL_EXPORT void vl_heap_update (VlHeap * self, int unsigned nodeIndex)
Parameters:
self Heap object instance.
nodeIndex node with changed priority.
The function restores the heap property after a node priority has been changed.
Example
Updating the third node of an heap of floats to have value 2.0:
 float * node = vl_heap_get_node_with_index (heap, 2) ;
 *node = 2.0F ;
 vl_heap_update (heap, 2) ;
Definition at line 330 of file heap.c.
References vl_heap_down(), and vl_heap_up().
© 2005-09 Andrea Vedaldi and Brian Fulkerson