VLFeat - Documentation - C API
VLFeat.org
Documentation - C API
heap-t.h File Reference
Heap template.
#include "generic.h"
#include "heap.h"
Functions
VL_INLINE void VL_HEAP_SWAP() NAME (T *a, T *b)
VL_INLINE void (T *nodeArray, int unsigned numNodes, int unsigned nodeIndex)
VL_INLINE void (T *nodeArray, int unsigned nodeIndex)
VL_INLINE void (T *nodeArray, int unsigned *numNodes)
Variables
VL_INLINE T *T * nodeArray
Detailed Description
Author:
Andrea Vedaldi
Definition in file heap-t.h.
Function Documentation
VL_INLINE void VL_HEAP_SWAP() NAME (T * a, T * b)
---------------------------------------------------------------
Definition at line 27 of file heap-t.h.
Referenced by void().
VL_INLINE void (T * nodeArray, int unsigned * numNodes)
---------------------------------------------------------------
Definition at line 102 of file heap-t.h.
References NAME(), and nodeArray.
VL_INLINE void (T * nodeArray, int unsigned nodeIndex)
---------------------------------------------------------------
Definition at line 80 of file heap-t.h.
References NAME(), nodeArray, and vl_heap_parent().
VL_INLINE void (T * nodeArray, int unsigned numNodes, int unsigned nodeIndex)
---------------------------------------------------------------
Definition at line 38 of file heap-t.h.
References NAME(), nodeArray, vl_heap_left_child(), and vl_heap_right_child().
Variable Documentation
VL_INLINE T* T* nodeArray
---------------------------------------------------------------
Definition at line 112 of file heap-t.h.
Referenced by void().
© 2005-09 Andrea Vedaldi and Brian Fulkerson