VLFeat - Documentation - C API
VLFeat.org
Documentation - C API
heap.c File Reference
Heap - Definition.
#include "heap.h"
#include <string.h>
Functions
VL_EXPORT void vl_heap_set_swap_func (VlHeap *self, void(*swap)(void *custom, void *a, void *b), void *customData)
Set function used to swap nodes.
VL_EXPORT VlHeap * vl_heap_new (void *nodes, int nodeSize, int(*compare)(void const *a, void const *b))
Create new heap object.
VL_EXPORT void vl_heap_delete (VlHeap *self)
Delete heap object.
VL_EXPORT void vl_heap_down (VlHeap *self, int nodeIndex)
Heap push-down operation.
VL_EXPORT void vl_heap_up (VlHeap *self, int nodeIndex)
Heap push-up operation.
VL_EXPORT void vl_heap_push (VlHeap *self)
Push a new node into the heap.
VL_EXPORT void * vl_heap_pop (VlHeap *self)
Pop the smallest node from the heap.
VL_EXPORT void vl_heap_update (VlHeap *self, int unsigned nodeIndex)
Update node priority.
Detailed Description
Author:
Andrea Vedaldi
Definition in file heap.c.
Function Documentation
VL_EXPORT void vl_heap_delete (VlHeap * self)
Parameters:
self heap object to delete.
Definition at line 170 of file heap.c.
References vl_free().
VL_EXPORT void vl_heap_down (VlHeap * self, int nodeIndex)
For internal use only.
Parameters:
self heap object instance.
nodeIndex index of the node to push down.
Definition at line 184 of file heap.c.
References vl_heap_get_node_with_index(), and vl_heap_parent().
Referenced by vl_heap_push(), and vl_heap_update().
VL_EXPORT VlHeap* vl_heap_new (void * nodes, int nodeSize, int(*)(void const *a, void const *b) compare)
Parameters:
nodes array of nodes.
nodeSize size in bytes of a node.
compare node comparison function.
Returns:
new heap object instance.
Definition at line 151 of file heap.c.
References vl_malloc().
VL_EXPORT void* vl_heap_pop (VlHeap * self)
Parameters:
self heap object instance.
Returns:
pointer do extracted node (or NULL if the heap is empty).
The function removes the root node from the heap and moves it to the firs position after the heap end. It then returns a pointer to it.
Example
To extract smallest value from an heap of floats:
 float * node = vl_heap_pop (heap) ;
Definition at line 296 of file heap.c.
References vl_heap_get_node_with_index(), and vl_heap_up().
VL_EXPORT void vl_heap_push (VlHeap * self)
Parameters:
self heap object instance.
The function adds to the heap the first node after the heap end.
Example
To add a node of value 1.0 to an heap of floats:
 float * node = vl_heap_get_node_with_index (heap, vl_heap_get_node_num (heap)) ;
 *node = 1.0F ;
 vl_heap_push (self) ;
Definition at line 272 of file heap.c.
References vl_heap_down().
VL_EXPORT void vl_heap_set_swap_func (VlHeap * self, void(*)(void *custom, void *a, void *b) swap, void * customData)
Parameters:
self heap object instance.
swap swap function.
customData pointer to data passed to the swap function.
The swap function swap is called whenever nodes are rearranged in the heap. swap must swap the node pointed by a with the node pointed by b.
You can customize the swap function to track the index of the nodes as they are rearranged in the heap.
Definition at line 133 of file heap.c.
VL_EXPORT void vl_heap_up (VlHeap * self, int nodeIndex)
For internal use only.
Parameters:
self heap object instance.
nodeIndex index of the node to push up.
Definition at line 213 of file heap.c.
References vl_heap_get_node_with_index(), vl_heap_left_child(), and vl_heap_right_child().
Referenced by vl_heap_pop(), and vl_heap_update().
VL_EXPORT void vl_heap_update (VlHeap * self, int unsigned nodeIndex)
Parameters:
self Heap object instance.
nodeIndex node with changed priority.
The function restores the heap property after a node priority has been changed.
Example
Updating the third node of an heap of floats to have value 2.0:
 float * node = vl_heap_get_node_with_index (heap, 2) ;
 *node = 2.0F ;
 vl_heap_update (heap, 2) ;
Definition at line 330 of file heap.c.
References vl_heap_down(), and vl_heap_up().
© 2005-09 Andrea Vedaldi and Brian Fulkerson