VLFeat - Documentation - C API
VLFeat.org
Documentation - C API
ikmeans_lloyd.tc File Reference
Integer K-Means - LLoyd Algorithm - Definition.
Functions
static void vl_ikm_init_lloyd (VlIKMFilt *f)
Helper function to initialize a filter for Lloyd algorithm.
static int vl_ikm_train_lloyd (VlIKMFilt *f, vl_uint8 const *data, int N)
LLoyd algorithm.
static void vl_ikm_push_lloyd (VlIKMFilt *f, vl_uint *asgn, vl_uint8 const *data, int N)
LLoyd algorithm.
Detailed Description
For internal use only.
Author:
Brian Fulkerson
Andrea Vedaldi
Definition in file ikmeans_lloyd.tc.
Function Documentation
static void vl_ikm_init_lloyd (VlIKMFilt * f) [static]
For internal use only.
Parameters:
f filter.
Definition at line 22 of file ikmeans_lloyd.tc.
Referenced by vl_ikm_init_helper().
static void vl_ikm_push_lloyd (VlIKMFilt * f, vl_uint * asgn, vl_uint8 const * data, int N) [static]
For internal use only.
Parameters:
f IKM quantizer.
asgn Assignments (out).
data Data to quantize.
N Number of data.
Definition at line 125 of file ikmeans_lloyd.tc.
References _VlIKMFilt::centers, _VlIKMFilt::K, _VlIKMFilt::M, and vl_ikm_push_one().
Referenced by vl_ikm_push().
static int vl_ikm_train_lloyd (VlIKMFilt * f, vl_uint8 const * data, int N) [static]
For internal use only.
Parameters:
f IKM quantizer.
data Training data.
N Number of traning data.
Definition at line 33 of file ikmeans_lloyd.tc.
References _VlIKMFilt::centers, _VlIKMFilt::max_niters, vl_free(), and vl_malloc().
Referenced by vl_ikm_train().
© 2005-09 Andrea Vedaldi and Brian Fulkerson