VLFeat - Documentation - C API
VLFeat.org
Documentation - C API
ikmeans_init.tc File Reference
Integer K-Means - Initialization - Definition.
#include "random.h"
Functions
static void alloc (VlIKMFilt *f, int M, int K)
Helper function to allocate memory for an IKM quantizer.
static void vl_ikm_init_helper (VlIKMFilt *f)
Helper function to initialize the quantizer.
VL_EXPORT void vl_ikm_init (VlIKMFilt *f, vl_ikm_acc const *centers, int M, int K)
Initialize quantizer with centers.
VL_EXPORT void vl_ikm_init_rand (VlIKMFilt *f, int M, int K)
Initialize quantizer with random centers.
VL_EXPORT void vl_ikm_init_rand_data (VlIKMFilt *f, vl_uint8 const *data, int M, int N, int K)
Initialize with centers from random data.
Detailed Description
For internal use only.
Author:
Andrea Vedaldi
Definition in file ikmeans_init.tc.
Function Documentation
static void alloc (VlIKMFilt * f, int M, int K) [static]
For internal use only.
Parameters:
f quantizer.
M data dimensionality.
K number of clusters.
Definition at line 51 of file ikmeans_init.tc.
References vl_free(), and vl_malloc().
Referenced by vl_ikm_init(), vl_ikm_init_rand(), and vl_ikm_init_rand_data().
VL_EXPORT void vl_ikm_init (VlIKMFilt * f, vl_ikm_acc const * centers, int M, int K)
Parameters:
f IKM quantizer.
centers centers.
M data dimensionality.
K number of clusters.
Definition at line 82 of file ikmeans_init.tc.
References alloc(), and vl_ikm_init_helper().
static void vl_ikm_init_helper (VlIKMFilt * f) [static]
Parameters:
f IKM quantizer.
Definition at line 65 of file ikmeans_init.tc.
References VL_IKM_ELKAN, vl_ikm_init_elkan(), vl_ikm_init_lloyd(), and VL_IKM_LLOYD.
Referenced by vl_ikm_init(), vl_ikm_init_rand(), and vl_ikm_init_rand_data().
VL_EXPORT void vl_ikm_init_rand (VlIKMFilt * f, int M, int K)
Parameters:
f IKM quantizer.
M data dimensionality.
K number of clusters.
Definition at line 100 of file ikmeans_init.tc.
References alloc(), vl_ikm_init_helper(), and vl_rand_uint32().
VL_EXPORT void vl_ikm_init_rand_data (VlIKMFilt * f, vl_uint8 const * data, int M, int N, int K)
Parameters:
f IKM quantizer.
data data.
M data dimensionality.
N number of data.
K number of clusters.
Definition at line 126 of file ikmeans_init.tc.
References alloc(), calc_dist2(), vl_free(), vl_ikm_init_helper(), vl_malloc(), and vl_rand_uint32().
Referenced by xmeans().
© 2005-09 Andrea Vedaldi and Brian Fulkerson