VLFeat - Documentation - C API
VLFeat.org
Documentation - C API
ikmeans_elkan.tc File Reference
Integer K-Means - Elkan Algorithm - Definition.
Functions
static unsigned int isqrt (unsigned long val)
static void vl_ikm_elkan_update_inter_dist (VlIKMFilt *f)
static void vl_ikm_init_elkan (VlIKMFilt *f)
Helper function to initialize filter for Triangle algorithm.
static int vl_ikm_train_elkan (VlIKMFilt *f, vl_uint8 const *data, int N)
Elkan algorithm.
static void vl_ikm_push_elkan (VlIKMFilt *f, vl_uint *asgn, vl_uint8 const *data, int N)
Elkan algorithm.
Detailed Description
For internal use only.
Author:
Andrea Vedaldi
Definition in file ikmeans_elkan.tc.
Function Documentation
static unsigned int isqrt (unsigned long val) [static]
For internal use only.
Square root of an integer value
Author:
Jim Ulery
Definition at line 21 of file ikmeans_elkan.tc.
Referenced by vl_ikm_train_elkan().
static void vl_ikm_elkan_update_inter_dist (VlIKMFilt * f) [static]
For internal use only.
Update inter cluster distance table.
Definition at line 39 of file ikmeans_elkan.tc.
References _VlIKMFilt::centers, and _VlIKMFilt::inter_dist.
Referenced by vl_ikm_init_elkan(), and vl_ikm_train_elkan().
static void vl_ikm_init_elkan (VlIKMFilt * f) [static]
For internal use only.
Parameters:
f filter.
Definition at line 68 of file ikmeans_elkan.tc.
References _VlIKMFilt::K, vl_free(), vl_ikm_elkan_update_inter_dist(), and vl_malloc().
Referenced by vl_ikm_init_helper().
static void vl_ikm_push_elkan (VlIKMFilt * f, vl_uint * asgn, vl_uint8 const * data, int N) [static]
For internal use only.
Parameters:
f IKM quantizer.
asgn Assignment of data to centers (out).
data Data to quantize.
N Number of data elements.
Definition at line 345 of file ikmeans_elkan.tc.
References _VlIKMFilt::centers, and VL_BIG_INT.
Referenced by vl_ikm_push().
static int vl_ikm_train_elkan (VlIKMFilt * f, vl_uint8 const * data, int N) [static]
For internal use only.
Parameters:
f IKM quantizer.
data Data to quantize.
N Number of data elements.
Definition at line 86 of file ikmeans_elkan.tc.
References _VlIKMFilt::centers, isqrt(), _VlIKMFilt::max_niters, VL_BIG_INT, vl_free(), vl_ikm_elkan_update_inter_dist(), vl_malloc(), and VL_PRINTF.
Referenced by vl_ikm_train().
© 2005-09 Andrea Vedaldi and Brian Fulkerson