VLFeat - Documentation - C API
VLFeat.org
Documentation - C API
kdtree.c File Reference
KD-tree - Definition.
#include "kdtree.h"
#include "generic.h"
#include "random.h"
#include "mathop.h"
Functions
int unsigned vl_kdtree_node_new (VlKDTree *tree, int unsigned parentIndex)
Allocate a new node from the tree pool.
static int vl_kdtree_compare_index_entries (void const *a, void const *b)
Compare KDTree index entries for sorting.
static void vl_kdtree_build_recursively (VlKDForest *forest, VlKDTree *tree, unsigned int nodeIndex, unsigned int dataBegin, unsigned int dataEnd, unsigned int depth)
Build KDTree recursively.
VL_EXPORT VlKDForest * vl_kdforest_new (int unsigned numDimensions, int unsigned numTrees)
Create new KDForest object.
VL_EXPORT void vl_kdforest_delete (VlKDForest *self)
Delete KDForest object.
VL_EXPORT void vl_kdforest_build (VlKDForest *self, int numData, float const *data)
Build KDTree from data.
VL_INLINE float calc_dist2 (float const *a, float const *b, int unsigned N)
VL_EXPORT int vl_kdforest_query_recursively (VlKDForest *self, VlKDTree *tree, int unsigned nodeIndex, VlKDForestNeighbor *neighbors, int unsigned numNeighbors, int unsigned *numAddedNeighbors, float dist, float const *query)
static void vl_kdtree_calc_bounds_recursively (VlKDTree *tree, int unsigned nodeIndex, float *searchBounds)
Compute tree bounds recursively.
VL_EXPORT int vl_kdforest_query (VlKDForest *self, VlKDForestNeighbor *neighbors, int unsigned numNeighbors, float const *query)
Query operation.
Detailed Description
Author:
Andrea Vedaldi
Definition in file kdtree.c.
Function Documentation
VL_INLINE float calc_dist2 (float const * a, float const * b, int unsigned N)
For internal use only.
Definition at line 373 of file kdtree.c.
Referenced by vl_ikm_init_rand_data(), and vl_kdforest_query_recursively().
VL_EXPORT void vl_kdforest_build (VlKDForest * self, int numData, float const * data)
Parameters:
tree KDTree object
numData number of data points.
data pointer to the data.
The function builds the KDTree by processing the data data. For efficiency, KDTree does not copy the data, but retains a pointer to it. Therefore the data must survive (and not change) until the KDTree is deleted.
Definition at line 342 of file kdtree.c.
References vl_kdtree_build_recursively(), vl_kdtree_node_new(), and vl_malloc().
VL_EXPORT void vl_kdforest_delete (VlKDForest * self)
Parameters:
tree KDForest object to delete
See also:
vl_kdforest_new
Definition at line 313 of file kdtree.c.
References vl_free().
VL_EXPORT VlKDForest* vl_kdforest_new (int unsigned numDimensions, int unsigned numTrees)
Parameters:
numDimensions data dimensionality.
numTrees number of trees in the forest.
Returns:
new KDForest.
Definition at line 282 of file kdtree.c.
References vl_malloc().
VL_EXPORT int vl_kdforest_query (VlKDForest * self, VlKDForestNeighbor * neighbors, int unsigned numNeighbors, float const * query)
Parameters:
self KDTree object instance.
neighbors list of nearest neighbors found (output).
numNeighbors number of nearest neighbors to find.
query query point.
Returns:
number of tree leaves visited.
A neighbor is represented by an instance of the structure VlKDForestNeighbor. Each entry contains the index of the neighbor (this is an index into the KDTree data) and its distance to the query point. Neighbors are sorted by increasing distance.
Definition at line 563 of file kdtree.c.
References _VlKDForestNeighbor::distance, _VlKDForestNeighbor::index, vl_calloc(), vl_free(), VL_INFINITY_F, vl_kdforest_query_recursively(), vl_kdtree_calc_bounds_recursively(), vl_malloc(), and VL_NAN_F.
VL_EXPORT int vl_kdforest_query_recursively (VlKDForest * self, VlKDTree * tree, int unsigned nodeIndex, VlKDForestNeighbor * neighbors, int unsigned numNeighbors, int unsigned * numAddedNeighbors, float dist, float const * query)
For internal use only.
Definition at line 402 of file kdtree.c.
References calc_dist2(), _VlKDForestNeighbor::distance, and _VlKDForestNeighbor::index.
Referenced by vl_kdforest_query().
static void vl_kdtree_build_recursively (VlKDForest * forest, VlKDTree * tree, unsigned int nodeIndex, unsigned int dataBegin, unsigned int dataEnd, unsigned int depth) [static]
For internal use only.
Parameters:
tree KDTree object.
nodeIndex node to process.
dataBegin begin of data for this node.
dataEnd end of data for this node.
depth depth of this node.
Definition at line 164 of file kdtree.c.
References _VlKDForest::data, _VlKDForest::numDimensions, _VlKDForest::splitHeapArray, _VlKDForest::splitHeapNumNodes, _VlKDForest::splitHeapSize, _VlKDForest::thresholdingMethod, vl_kdtree_compare_index_entries(), vl_kdtree_node_new(), VL_MIN, and vl_rand_uint32().
Referenced by vl_kdforest_build().
static void vl_kdtree_calc_bounds_recursively (VlKDTree * tree, int unsigned nodeIndex, float * searchBounds) [static]
For internal use only.
Parameters:
self KDTree object instance.
nodeIndex node index to start from.
searchBounds 2 x numDimension array of bounds.
Definition at line 526 of file kdtree.c.
Referenced by vl_kdforest_query().
static int vl_kdtree_compare_index_entries (void const * a, void const * b) [static]
For internal use only.
Definition at line 141 of file kdtree.c.
Referenced by vl_kdtree_build_recursively().
int unsigned vl_kdtree_node_new (VlKDTree * tree, int unsigned parentIndex)
For internal use only.
Definition at line 118 of file kdtree.c.
Referenced by vl_kdforest_build(), and vl_kdtree_build_recursively().
© 2005-09 Andrea Vedaldi and Brian Fulkerson