VLFeat - Documentation - C API
VLFeat.org
Documentation - C API
kdtree.h File Reference
KD-tree.
#include "generic.h"
Data Structures
struct _VlKDForestNeighbor
Neighbor of a query point.
struct _VlKDForest
KDForest object.
Typedefs
typedef enum
_VlKDTreeThresholdingMethod VlKDTreeThresholdingMethod
Thresholding method.
typedef struct _VlKDForestNeighbor VlKDForestNeighbor
Neighbor of a query point.
typedef struct _VlKDForest VlKDForest
KDForest object.
Enumerations
enum _VlKDTreeThresholdingMethod
Thresholding method.
Functions
Creatind and disposing
VL_EXPORT VlKDForest * vl_kdforest_new (int unsigned numDimensions, int unsigned numTrees)
Create new KDForest object.
VL_EXPORT void vl_kdforest_delete (VlKDForest *self)
Delete KDForest object.
Building and querying
VL_EXPORT void vl_kdforest_build (VlKDForest *self, int numData, float const *data)
Build KDTree from data.
VL_EXPORT int vl_kdforest_query (VlKDForest *self, VlKDForestNeighbor *neighbors, int unsigned numNeighbors, float const *query)
Query operation.
Retrieving and setting parameters
VL_INLINE int unsigned vl_kdforest_get_depth_of_tree (VlKDForest const *self, int unsigned treeIndex)
Get the detph of a given tree.
VL_INLINE int unsigned vl_kdforest_get_num_nodes_of_tree (VlKDForest const *self, int unsigned treeIndex)
Get the number of nodes of a given tree.
VL_INLINE int unsigned vl_kdforest_get_num_trees (VlKDForest const *self)
Get the number of trees in the forest.
VL_INLINE void vl_kdforest_set_max_num_comparisons (VlKDForest *self, int unsigned n)
Set the maximum number of comparisons for a search.
VL_INLINE int unsigned vl_kdforest_get_max_num_comparisons (VlKDForest *self)
Get the maximum number of comparisons for a search.
VL_INLINE void vl_kdforest_set_thresholding_method (VlKDForest *self, VlKDTreeThresholdingMethod method)
Set the thresholding method.
VL_INLINE
VlKDTreeThresholdingMethod vl_kdforest_get_thresholding_method (VlKDForest const *self)
Get the thresholding method.
Detailed Description
VlKDTree implements a KD-tree object data structure useful to index moderately dimensional vector spaces. It can be used to quickly match two groups of feature descriptors.
Overview
Technical details
To create a VlKDForest object use vl_kdforest_new specifying the dimensionality of the data and the number of trees in the forest. With one tree only, the algorithm is analogous to [1] (best-bin KDTree). Multiple trees correspond to the randomized KDTree forest as in [2,3].
To let the KD-tree index some data use vl_kdforest_build. Note that for efficiency KD-tree does not copy the data but retains a pointer to it. Therefore the data must exist (and not change) until the KD-tree is deleted. To delete the KD-tree object, use vl_kdforest_delete.
To find the N nearest neighbors to a query point use vl_kdforest_query. To set a maximum number of comparisons per query and calculate approximate nearest neighbors use vl_kdforest_set_max_num_comparisons.
See also:
References
KDTree implements the best-bin-first kd-tree of [1]. Given a set of points , the algorithm recursively partitions the d dimensional Euclidean space into (hyper-) rectangles.
Partitions are organized into a binary tree with the root corresponding to the whole space . The algorithm refines each partition by dividing it into two halves by thresholding along a given dimension. Both the splitting dimension and the threshold are determined as a statistic of the data points contained in the partition. The splitting dimension is the one which has largest sample variance and the splitting threshold is either the sample mean or the median. Leaves are atomic partitions and they contain a list of zero or more data points (typically one).
Querying amounts to finding the N data points closer to a given query point . This is done by branch-and-bound. A search state is an active partition (initially the root) and it is weighed by the lower bound on the distance of any point in the partition and the query point. Such a lower bound is trivial to compute because partitions are hyper-rectangles.
[1] J. S. Beis and D. G. Lowe. Shape indexing using approximate nearest-neighbour search in high-dimensional spaces. In Proc. CVPR, 1997.
[2] C. Silpa-Anan and R. Hartley. Optimised KD-trees for fast image descriptor matching. In Proc. CVPR, 2008.
[3] M. Muja and D. G. Lowe. Fast approximate nearest neighbors with automatic algorithmic configuration. In Proc. VISAPP, 2009.
Author:
Andrea Vedaldi
Definition in file kdtree.h.
Function Documentation
VL_EXPORT void vl_kdforest_build (VlKDForest * self, int numData, float const * data)
Parameters:
tree KDTree object
numData number of data points.
data pointer to the data.
The function builds the KDTree by processing the data data. For efficiency, KDTree does not copy the data, but retains a pointer to it. Therefore the data must survive (and not change) until the KDTree is deleted.
Definition at line 342 of file kdtree.c.
References vl_kdtree_build_recursively(), vl_kdtree_node_new(), and vl_malloc().
VL_EXPORT void vl_kdforest_delete (VlKDForest * self)
Parameters:
tree KDForest object to delete
See also:
vl_kdforest_new
Definition at line 313 of file kdtree.c.
References vl_free().
int unsigned vl_kdforest_get_depth_of_tree (VlKDForest const * self, int unsigned treeIndex)
Parameters:
self KDForest object.
treeIndex index of the tree.
Returns:
number of trees.
Definition at line 158 of file kdtree.h.
int unsigned vl_kdforest_get_max_num_comparisons (VlKDForest * self)
Parameters:
self KDForest object.
Returns:
maximum number of leaves.
See also:
vl_kdforest_set_max_num_comparisons.
Definition at line 205 of file kdtree.h.
int unsigned vl_kdforest_get_num_nodes_of_tree (VlKDForest const * self, int unsigned treeIndex)
Parameters:
self KDForest object.
treeIndex index of the tree.
Returns:
number of trees.
Definition at line 144 of file kdtree.h.
int unsigned vl_kdforest_get_num_trees (VlKDForest const * self)
Parameters:
self KDForest object.
Returns:
number of trees.
Definition at line 172 of file kdtree.h.
VL_INLINE VlKDTreeThresholdingMethod vl_kdforest_get_thresholding_method (VlKDForest const * self)
Parameters:
self KDForest object.
Returns:
thresholding method.
See also:
vl_kdforest_set_thresholding_method
Definition at line 235 of file kdtree.h.
VL_EXPORT VlKDForest* vl_kdforest_new (int unsigned numDimensions, int unsigned numTrees)
Parameters:
numDimensions data dimensionality.
numTrees number of trees in the forest.
Returns:
new KDForest.
Definition at line 282 of file kdtree.c.
References vl_malloc().
VL_EXPORT int vl_kdforest_query (VlKDForest * self, VlKDForestNeighbor * neighbors, int unsigned numNeighbors, float const * query)
Parameters:
self KDTree object instance.
neighbors list of nearest neighbors found (output).
numNeighbors number of nearest neighbors to find.
query query point.
Returns:
number of tree leaves visited.
A neighbor is represented by an instance of the structure VlKDForestNeighbor. Each entry contains the index of the neighbor (this is an index into the KDTree data) and its distance to the query point. Neighbors are sorted by increasing distance.
Definition at line 563 of file kdtree.c.
References _VlKDForestNeighbor::distance, _VlKDForestNeighbor::index, vl_calloc(), vl_free(), VL_INFINITY_F, vl_kdforest_query_recursively(), vl_kdtree_calc_bounds_recursively(), vl_malloc(), and VL_NAN_F.
void vl_kdforest_set_max_num_comparisons (VlKDForest * self, int unsigned n)
Parameters:
self KDForest object.
n maximum number of leaves.
This function sets the maximum number of comparisons for a nearest neighbor search. Setting it to 0 means unbounded comparisons.
See also:
vl_kdforest_query, vl_kdforest_get_max_num_comparisons.
Definition at line 190 of file kdtree.h.
VL_INLINE void vl_kdforest_set_thresholding_method (VlKDForest * self, VlKDTreeThresholdingMethod method)
Parameters:
self KDForest object.
method one of VlKDTreeThresholdingMethod.
See also:
vl_kdforest_get_thresholding_method
Definition at line 219 of file kdtree.h.
© 2005-09 Andrea Vedaldi and Brian Fulkerson