VLFeat - Documentation - C API
VLFeat.org
Documentation - C API
mathop.h File Reference
Math operations.
#include "generic.h"
#include <math.h>
Defines
#define VL_LOG_OF_2 0.693147180559945
Logarithm of 2 (math constant).
#define VL_PI 3.141592653589793
Pi (math constant).
#define VL_EPSILON_F 1.19209290E-07F
IEEE single precision epsilon (math constant).
#define VL_EPSILON_D 2.220446049250313e-16
IEEE double precision epsilon (math constant).
#define VL_NAN_F (vl_nan_f.value)
IEEE single precision NaN (not signaling).
#define VL_INFINITY_F (vl_infinity_f.value)
IEEE single precision positive infinity (not signaling).
#define VL_NAN_D (vl_nan_d.value)
IEEE double precision NaN (not signaling).
#define VL_INFINITY_D (vl_infinity_d.value)
IEEE double precision positive infinity (not signaling).
Typedefs
typedef enum
_VlVectorComparisonType VlVectorComparisonType
Vector comparison types.
Enumerations
enum _VlVectorComparisonType {
VlDistanceL1, VlDistanceL2, VlDistanceChi2, VlKernelL1,
VlKernelL2, VlKernelChi2
}
Vector comparison types.
Functions
ui16 VL_FAST_SQRT_UI (vl_uint8, ui8) typedef float(*VlFloatVectorComparisonFunction)(vl_size dimension
VL_INLINE float vl_mod_2pi_f (float x)
Fast mod(x, 2 * VL_PI).
VL_INLINE double vl_mod_2pi_d (double x)
Fast mod(x, 2 * VL_PI).
VL_INLINE int vl_floor_f (float x)
Fast (int) floor(x).
VL_INLINE int vl_floor_d (double x)
Fast (int) floor(x).
VL_INLINE float vl_abs_f (float x)
Fast abs(x).
VL_INLINE double vl_abs_d (double x)
Fast abs(x).
VL_INLINE float vl_fast_atan2_f (float y, float x)
Fast atan2 approximation.
VL_INLINE double vl_fast_atan2_d (double y, double x)
Fast atan2 approximation.
VL_INLINE float vl_fast_resqrt_f (float x)
Fast resqrt approximation.
VL_INLINE double vl_fast_resqrt_d (double x)
Fast resqrt approximation.
VL_INLINE float vl_fast_sqrt_f (float x)
Fast sqrt approximation.
VL_INLINE double vl_fast_sqrt_d (float x)
Fast sqrt approximation.
VL_INLINE vl_uint32 vl_fast_sqrt_ui32 (vl_uint32 x)
Fast sqrt approximation.
VL_INLINE vl_uint16 vl_fast_sqrt_ui16 (vl_uint16 x)
Fast sqrt approximation.
VL_INLINE vl_uint8 vl_fast_sqrt_ui8 (vl_uint8 x)
Fast sqrt approximation.
VL_EXPORT void vl_eval_vector_comparison_on_all_pairs_f (float *result, vl_size dimension, float const *X, vl_size numDataX, float const *Y, vl_size numDataY, VlFloatVectorComparisonFunction function)
VL_EXPORT void vl_eval_vector_comparison_on_all_pairs_d (double *result, vl_size dimension, double const *X, vl_size numDataX, double const *Y, vl_size numDataY, VlDoubleVectorComparisonFunction)
Variables
union {
} vl_nan_f
IEEE single precision quiet NaN constant.
union {
} vl_infinity_f
IEEE single precision infinity constant.
union {
} vl_nan_d
IEEE double precision quiet NaN constant.
union {
} vl_infinity_d
IEEE double precision infinity constant.
Detailed Description
Author:
Andrea Vedaldi
Definition in file mathop.h.
Define Documentation
#define VL_EPSILON_D 2.220446049250313e-16
1.0 + VL_EPSILON_D is the smallest representable double precision number greater than 1.0. Numerically, VL_EPSILON_D is equal to .
Definition at line 40 of file mathop.h.
Referenced by vl_fast_atan2_d(), and vl_sift_calc_raw_descriptor().
#define VL_EPSILON_F 1.19209290E-07F
1.0F + VL_EPSILON_F is the smallest representable single precision number greater than 1.0F. Numerically, VL_EPSILON_F is equal to .
Definition at line 32 of file mathop.h.
Referenced by _vl_dsift_normalize_histogram(), normalize_histogram(), vl_fast_atan2_f(), and vl_pgm_write_f().
Enumeration Type Documentation
enum _VlVectorComparisonType
Enumerator:
VlDistanceL1 l1 distance
VlDistanceL2 l2 distance
VlDistanceChi2 Chi2 distance
VlKernelL1 l1 kernel
VlKernelL2 l2 kernel
VlKernelChi2 Chi2 kernel
Definition at line 446 of file mathop.h.
Function Documentation
VL_INLINE double vl_abs_d (double x)
Parameters:
x argument.
Returns:
abs(x)
Definition at line 165 of file mathop.h.
Referenced by vl_fast_atan2_d(), and vl_sift_detect().
VL_INLINE float vl_abs_f (float x)
Parameters:
x argument.
Returns:
abs(x)
Definition at line 155 of file mathop.h.
Referenced by vl_fast_atan2_f(), vl_sift_calc_keypoint_descriptor(), and vl_sift_calc_raw_descriptor().
vl_eval_vector_comparison_on_all_pairs_d (double * result, vl_size dimension, double const * X, vl_size numDataX, double const * Y, vl_size numDataY, VlDoubleVectorComparisonFunction)
Parameters:
result comparison matrix (output).
dimension number of vector components (rows of X and Y).
X data matrix X.
Y data matrix Y.
numDataX number of vectors in X (columns of X)
numDataY number of vectros in Y (columns of Y)
comparison vector comparison function.
The function evaluates function on all pairs of columns from matrices X and Y, filling a numDataX by numDataY matrix.
If Y is a null pointer the function compares all columns from X with themselves.
vl_eval_vector_comparison_on_all_pairs_f (float * result, vl_size dimension, float const * X, vl_size numDataX, float const * Y, vl_size numDataY, VlFloatVectorComparisonFunction function)
Parameters:
result comparison matrix (output).
dimension number of vector components (rows of X and Y).
X data matrix X.
Y data matrix Y.
numDataX number of vectors in X (columns of X)
numDataY number of vectros in Y (columns of Y)
comparison vector comparison function.
The function evaluates function on all pairs of columns from matrices X and Y, filling a numDataX by numDataY matrix.
If Y is a null pointer the function compares all columns from X with themselves.
VL_INLINE double vl_fast_atan2_d (double y, double x)
Parameters:
y argument.
x argument.
The function computes a relatively rough but fast approximation of atan2(y,x).
Algorithm
The algorithm approximates the function , with a third order polynomial . To fit the polynomial we impose the constraints
The last degree of freedom is fixed by minimizing the error, which yields
with maximum error of 0.0061 radians at 0.35 degrees.
Returns:
Approximation of atan2(y,x).
Definition at line 234 of file mathop.h.
References vl_abs_d(), VL_EPSILON_D, and VL_PI.
VL_INLINE float vl_fast_atan2_f (float y, float x)
Parameters:
y argument.
x argument.
The function computes a relatively rough but fast approximation of atan2(y,x).
Algorithm
The algorithm approximates the function , with a third order polynomial . To fit the polynomial we impose the constraints
The last degree of freedom is fixed by minimizing the error, which yields
with maximum error of 0.0061 radians at 0.35 degrees.
Returns:
Approximation of atan2(y,x).
Definition at line 214 of file mathop.h.
References vl_abs_f(), VL_EPSILON_F, and VL_PI.
Referenced by vl_dsift_process().
VL_INLINE double vl_fast_resqrt_d (double x)
Parameters:
x argument.
The function quickly computes an approximation of .
Algorithm
The goal is to compute , which we do by finding the solution of by two Newton steps. Each Newton iteration is given by
which yields a simple polynomial update rule.
The clever bit (attributed to either J. Carmack or G. Tarolli) is the way an initial guess is chosen.
See also:
Inverse Sqare Root.
Returns:
Approximation of resqrt(x).
Definition at line 311 of file mathop.h.
Referenced by vl_fast_sqrt_d().
VL_INLINE float vl_fast_resqrt_f (float x)
Parameters:
x argument.
The function quickly computes an approximation of .
Algorithm
The goal is to compute , which we do by finding the solution of by two Newton steps. Each Newton iteration is given by
which yields a simple polynomial update rule.
The clever bit (attributed to either J. Carmack or G. Tarolli) is the way an initial guess is chosen.
See also:
Inverse Sqare Root.
Returns:
Approximation of resqrt(x).
Definition at line 286 of file mathop.h.
Referenced by vl_fast_sqrt_f().
VL_INLINE double vl_fast_sqrt_d (float x)
Parameters:
x argument.
Returns:
Approximation of sqrt(x).
The function computes a fast approximation of sqrt(x).
Floating-point algorithm
For the floating point cases, the function uses vl_fast_resqrt_f (or vl_fast_resqrt_d) to compute x * vl_fast_resqrt_f(x).
Integer algorithm
We seek for the largest integer y such that . Write where the binary expansion of the various variable is
Assume w known. Expanding the square and using the fact that , we obtain the following constraint for and z:
A necessary condition for is that this equation is satisfied for (as the second term is always non-negative). In fact, this condition is also sufficient, since we are looking for the largest solution y.
This yields the following iterative algorithm. First, note that if x is stored in n bits, where n is even, then the integer square root does not require more than bit to be stored. Thus initially, and . Then, at each iteration the equation is tested, determining in this order.
Definition at line 393 of file mathop.h.
References vl_fast_resqrt_d().
VL_INLINE float vl_fast_sqrt_f (float x)
Parameters:
x argument.
Returns:
Approximation of sqrt(x).
The function computes a fast approximation of sqrt(x).
Floating-point algorithm
For the floating point cases, the function uses vl_fast_resqrt_f (or vl_fast_resqrt_d) to compute x * vl_fast_resqrt_f(x).
Integer algorithm
We seek for the largest integer y such that . Write where the binary expansion of the various variable is
Assume w known. Expanding the square and using the fact that , we obtain the following constraint for and z:
A necessary condition for is that this equation is satisfied for (as the second term is always non-negative). In fact, this condition is also sufficient, since we are looking for the largest solution y.
This yields the following iterative algorithm. First, note that if x is stored in n bits, where n is even, then the integer square root does not require more than bit to be stored. Thus initially, and . Then, at each iteration the equation is tested, determining in this order.
Definition at line 387 of file mathop.h.
References vl_fast_resqrt_f().
Referenced by _vl_dsift_normalize_histogram(), normalize_histogram(), and vl_dsift_process().
ui16 VL_FAST_SQRT_UI (vl_uint8 , ui8)
VL_INLINE vl_uint16 vl_fast_sqrt_ui16 (vl_uint16 x)
Parameters:
x argument.
Returns:
Approximation of sqrt(x).
The function computes a fast approximation of sqrt(x).
Floating-point algorithm
For the floating point cases, the function uses vl_fast_resqrt_f (or vl_fast_resqrt_d) to compute x * vl_fast_resqrt_f(x).
Integer algorithm
We seek for the largest integer y such that . Write where the binary expansion of the various variable is
Assume w known. Expanding the square and using the fact that , we obtain the following constraint for and z:
A necessary condition for is that this equation is satisfied for (as the second term is always non-negative). In fact, this condition is also sufficient, since we are looking for the largest solution y.
This yields the following iterative algorithm. First, note that if x is stored in n bits, where n is even, then the integer square root does not require more than bit to be stored. Thus initially, and . Then, at each iteration the equation is tested, determining in this order.
VL_INLINE vl_uint32 vl_fast_sqrt_ui32 (vl_uint32 x)
Parameters:
x argument.
Returns:
Approximation of sqrt(x).
The function computes a fast approximation of sqrt(x).
Floating-point algorithm
For the floating point cases, the function uses vl_fast_resqrt_f (or vl_fast_resqrt_d) to compute x * vl_fast_resqrt_f(x).
Integer algorithm
We seek for the largest integer y such that . Write where the binary expansion of the various variable is
Assume w known. Expanding the square and using the fact that , we obtain the following constraint for and z:
A necessary condition for is that this equation is satisfied for (as the second term is always non-negative). In fact, this condition is also sufficient, since we are looking for the largest solution y.
This yields the following iterative algorithm. First, note that if x is stored in n bits, where n is even, then the integer square root does not require more than bit to be stored. Thus initially, and . Then, at each iteration the equation is tested, determining in this order.
VL_INLINE vl_uint8 vl_fast_sqrt_ui8 (vl_uint8 x)
Parameters:
x argument.
Returns:
Approximation of sqrt(x).
The function computes a fast approximation of sqrt(x).
Floating-point algorithm
For the floating point cases, the function uses vl_fast_resqrt_f (or vl_fast_resqrt_d) to compute x * vl_fast_resqrt_f(x).
Integer algorithm
We seek for the largest integer y such that . Write where the binary expansion of the various variable is
Assume w known. Expanding the square and using the fact that , we obtain the following constraint for and z:
A necessary condition for is that this equation is satisfied for (as the second term is always non-negative). In fact, this condition is also sufficient, since we are looking for the largest solution y.
This yields the following iterative algorithm. First, note that if x is stored in n bits, where n is even, then the integer square root does not require more than bit to be stored. Thus initially, and . Then, at each iteration the equation is tested, determining in this order.
VL_INLINE int vl_floor_d (double x)
Parameters:
x argument.
Returns:
(int) floor(x)
Definition at line 139 of file mathop.h.
Referenced by fast_expn(), vl_sift_calc_keypoint_orientations(), and vl_sift_keypoint_init().
VL_INLINE int vl_floor_f (float x)
Parameters:
x argument.
Returns:
(int) floor(x)
Definition at line 130 of file mathop.h.
Referenced by vl_dsift_process(), vl_sift_calc_keypoint_descriptor(), and vl_sift_calc_raw_descriptor().
VL_INLINE double vl_mod_2pi_d (double x)
Parameters:
x input value.
The function is optimized for small absolute values of x.
The result is guaranteed to be not smaller than 0. However, due to finite numerical precision and rounding errors, the result can be equal to 2 * VL_PI (for instance, if x is a very small negative number).
Returns:
mod(x, 2 * VL_PI)
Definition at line 113 of file mathop.h.
References VL_PI.
VL_INLINE float vl_mod_2pi_f (float x)
Parameters:
x input value.
The function is optimized for small absolute values of x.
The result is guaranteed to be not smaller than 0. However, due to finite numerical precision and rounding errors, the result can be equal to 2 * VL_PI (for instance, if x is a very small negative number).
Returns:
mod(x, 2 * VL_PI)
Definition at line 105 of file mathop.h.
References VL_PI.
Referenced by vl_dsift_process(), vl_sift_calc_keypoint_descriptor(), and vl_sift_calc_raw_descriptor().
© 2005-09 Andrea Vedaldi and Brian Fulkerson