VLFeat - Documentation - C API
VLFeat.org
Documentation - C API
mexutils.h File Reference
MEX utilities.
#include "mex.h"
#include <vl/generic.h>
#include <ctype.h>
#include <stdio.h>
#include <stdarg.h>
Data Structures
struct _uMexOption
MEX option.
Defines
#define VL_USE_MATLAB_ENV
Let VLFeat use MATLAB memory allocation/logging facilities.
#define VLMX_EIA(...) mxuError("invalidArgument", __VA_ARGS__)
Generate invalid argument error.
Typedefs
typedef struct _uMexOption uMexOption
MEX option type.
Functions
static mxArray * uCreateNumericArray (mwSize ndim, const mwSize *dims, mxClassID classid, void *data)
Create array with pre-allocated data.
static mxArray * uCreateNumericMatrix (int M, int N, mxClassID classid, void *data)
Create an array with pre-allocated data.
static mxArray * uCreateScalar (double x)
Create a plain scalar.
static int uIsScalar (const mxArray *A)
Is the array a numeric scalar?
static vl_bool uIsPlainArray (const mxArray *A)
Is the array plain matrix?
static int uIsMatrix (const mxArray *A, int M, int N)
Is the array a numeric matrix?
static int uIsVector (const mxArray *A, int N)
Is the array a vector?
static int uIsReal (const mxArray *A)
Is the array real?
static int uIsRealScalar (const mxArray *A)
Is the array real and scalar?
static int uIsRealMatrix (const mxArray *A, int M, int N)
Is the array a real matrix?
static int uIsRealVector (const mxArray *A, int N)
Is the array a real vector?
static int uIsRealArray (const mxArray *A, int D, int *dims)
Is the array real with specified dimensions?
static int uIsString (const mxArray *A, int L)
Is the array a string?
void mxuError (char const *errorId, char const *errorMessage,...)
Generate MEX error with VLFeat format.
void uErrMsgTxt (char const *format,...)
Formatted mexErrMsgTxt().
static int uStrICmp (const char *s1, const char *s2)
Case insensitive string comparison.
static int uNextOption (mxArray const *args[], int nargs, uMexOption const *options, int *next, mxArray const **optarg)
Process next option.
Check for array attributes
VL_INLINE vl_bool vlmxIsOfClass (mxArray const *array, mxClassID classId)
Check if a MATLAB array is of a prescribed class.
VL_INLINE vl_bool vlmxIsReal (mxArray const *array)
Check if a MATLAB array is real.
Check for scalar, vector and matrix arrays
VL_INLINE vl_bool vlmxIsScalar (mxArray const *array)
Check if a MATLAB array is scalar.
VL_INLINE vl_bool vlmxIsVector (mxArray const *array, vl_index numElements)
Check if a MATLAB array is a vector.
VL_INLINE vl_bool vlmxIsMatrix (mxArray const *array, vl_index M, vl_index N)
Check if a MATLAB array is a matrix.
Check for plain arrays
VL_INLINE vl_bool vlmxIsPlainScalar (mxArray const *array)
Check if a MATLAB array is plain scalar.
VL_INLINE vl_bool vlmxIsPlainVector (mxArray const *array, vl_index numElements)
Check if a MATLAB array is a plain vector.
VL_INLINE vl_bool vlmxIsPlainMatrix (mxArray const *array, vl_index M, vl_index N)
Check if a MATLAB array is a plain matrix.
Detailed Description
Author:
Andrea Vedaldi
This header file provides helper functions for writing MATLAB MEX files.
VLFeat environment
Array tests
Parsing options
When the VLFeat DLL is linked to a MATLAB MEX files, at run time the MEX file must configure VLFeat to use MATLAB memory allocation and logging functions. This can be obtained by calling the macro VL_USE_MATLAB_ENV as the first line of each MEX file which is linked to the VLFeat DLL.
MATLAB supports a variety of array types. Most MEX file arguments are restricted to a few types and must be properly checked at run time. mexutils.h provides some helper functions to make it simpler to check such arguments. MATLAB basic array types are:
Numeric array: mxDOUBLE_CLASS, mxSINGLE_CLASS, mxINT8_CLASS, mxUINT8_CLASS, mxINT16_CLASS, mxUINT16_CLASS, mxINT32_CLASS, mxUINT32_CLASS. Moreover:
all such types have a real component
all such types may have a imaginary component
mxDOUBLE_LCASS arrays with two dimensions can be sparse.
Logical array (mxLOGICAL_CLASS).
Character array (mxCHAR_CLASS).
The other MATLAB array types are:
Struct array (mxSTRUCT_CLASS).
Cell array (mxCELL_CLASS).
Custom class array (mxCLASS_CLASS).
Unkown type array (mxUNKNOWN_CLASS).
VLFeat defines a number of common classes of arrays and corresponding tests.
Scalar array is a non-sparse array with exactly one element. Note that the array may have an arbitrary number of dimensions, and be of any numeric or other type. All dimensions are singleton (which is implied by having exactly one element). Use vlmxIsScalar to test if an array is scalar.
Vector array is a non-sparse array which is either empty (empty vector) or has at most one non-singleton dimension. The array can be of any numeric or other type. The elements of such a MATLAB array are stored as a plain C array with a number of elements equal to the number of elements in the array (obtained with mxGetNumberOfElements). Use vlmxIsVector to test if an array is a vector.
Matrix array is a non-sparse array for which all dimensions beyond the first two are singleton, or a non-sparse array which is empty and for which at least one of the first two dimensions is zero. The array can be of any numeric or other type. The non-singleton dimensions can be zero (empty matrix), one, or more. The element of such a MATLAB array are stored as a C array in column major order and its dimensions can be obtained by mxGetM and mxGetN. Use vlmxIsMatrix to test if an array is a mtarix.
Real array is a numeric array (as for mxIsNumeric) without a complex component. Use vlmxIsReal to check if an array is real.
Use vlmxIsOfClass to check if an array is of a prescribed (storage) class, such as mxDOUBLE_CLASS.
Plain scalar, vector, and matrix are a scalar, vector, and matrix arrays which are real and of class mxDOUBLE_CLASS. Use vlmxIsPlainScalar, vlmxIsPlainVector and vlmxIsPlainMatrix to check this.
It is common to pass optional arguments to a MEX file as option type-value pairs. Here type is a string identifying the option and value is a MATLAB array specifing its value. The function uNextOption can be used to simplify parsing a list of such arguments (similar to UNIX getopt). The functions mxuError and mxuWarning are shortcuts to specify VLFeat formatted errors.
Definition in file mexutils.h.
Define Documentation
#define VL_USE_MATLAB_ENV
Value:
vl_set_alloc_func (mxMalloc, mxRealloc, mxCalloc, mxFree) ;   \
  vl_set_printf_func (mexPrintf) ;
This makes VLFeat use MATLAB version of the memory allocation and logging functions.
Definition at line 320 of file mexutils.h.
Typedef Documentation
typedef struct _uMexOption uMexOption
See also:
_uMexOption
Definition at line 773 of file mexutils.h.
Function Documentation
void mxuError (char const * errorId, char const * errorMessage, ...)
Parameters:
errorId error ID string.
errorMessage error message C-style format string.
... format string arguments.
The function invokes mxErrMsgTxtAndId.
Definition at line 700 of file mexutils.h.
static mxArray* uCreateNumericArray (mwSize ndim, const mwSize * dims, mxClassID classid, void * data) [static]
Parameters:
ndim number of dimensions.
dims dimensions.
classid storage class ID.
data pre-allocated data.
If data is set to NULL, the data is allocated from the heap. If data is a buffer allocated by mxMalloc, then this buffer is used as data.
Returns:
new array.
Definition at line 340 of file mexutils.h.
static mxArray* uCreateNumericMatrix (int M, int N, mxClassID classid, void * data) [static]
Parameters:
M number of rows.
N number of columns.
classid class ID.
data pre-allocated data.
If data is set to NULL, the data is allocated from the heap. If data is a buffer allocated by mxMalloc, then this buffer is used as data.
Returns:
new array.
Definition at line 373 of file mexutils.h.
static mxArray* uCreateScalar (double x) [static]
Parameters:
x inital value.
Returns:
new array.
Definition at line 398 of file mexutils.h.
void uErrMsgTxt (char const * format, ...)
Parameters:
format format string (for sprintf).
... format string arguments.
Definition at line 743 of file mexutils.h.
static int uIsMatrix (const mxArray * A, int M, int N) [static]
Deprecated:
Array tests
Parameters:
A array to test.
M number of rows.
N number of columns.
The array A satisfies the test if:
It is numeric.
It as two dimensions.
M < 0 or the number of rows is equal to M.
N < 0 or the number of columns is equal to N.
Returns:
test result.
Definition at line 496 of file mexutils.h.
Referenced by uIsVector().
static vl_bool uIsPlainArray (const mxArray * A) [static]
Deprecated:
Array tests
Parameters:
A array to test.
The array A satisfies the test if:
It is a plain matrix
M < 0 or the number of rows is equal to M.
N < 0 or the number of columns is equal to N.
Returns:
test result.
Definition at line 441 of file mexutils.h.
static int uIsReal (const mxArray * A) [static]
Deprecated:
Array tests
Parameters:
A array to test.
An array satisfies the test if:
The storage class is DOUBLE.
There is no imaginary part.
Returns:
test result.
Definition at line 541 of file mexutils.h.
Referenced by uIsRealScalar().
static int uIsRealArray (const mxArray * A, int D, int * dims) [static]
Deprecated:
Array tests
Parameters:
A array to check.
D number of dimensions.
dims dimensions.
The array A satisfies the test if:
It is real (see uIsReal()).
ndims < 0 or it has ndims dimensions and
for each element of dims, either that element is negative or it is equal to the corresponding dimension of the array.
Returns:
test result.
Definition at line 636 of file mexutils.h.
static int uIsRealMatrix (const mxArray * A, int M, int N) [static]
Deprecated:
Array tests
Parameters:
A array to test.
M number of rows.
N number of columns.
The array A satisfies the test if:
It is real (see uIsReal()).
It as two dimensions.
M < 0 or the number of rows is equal to M.
N < 0 or the number of columns is equal to N.
Returns:
test result.
Definition at line 586 of file mexutils.h.
Referenced by uIsRealVector().
static int uIsRealScalar (const mxArray * A) [static]
Deprecated:
Array tests
Parameters:
A array to test.
An array is real and scalar if:
It is real (see uIsReal()).
It as only one element.
Returns:
test result.
Definition at line 562 of file mexutils.h.
References uIsReal().
static int uIsRealVector (const mxArray * A, int N) [static]
Deprecated:
Array tests
Parameters:
A array to test.
N number of elements.
The array A satisfies the test if
It is a real matrix (see uIsRealMatrix()).
It has a singleton dimension.
N < 0 or the other dimension is equal to N.
Returns:
test result.
Definition at line 612 of file mexutils.h.
References uIsRealMatrix().
static int uIsScalar (const mxArray * A) [static]
Deprecated:
Array tests
Parameters:
A array to test.
An array is numeric and scalar if:
It is numeric.
It as exactly one element.
Returns:
test result.
Definition at line 419 of file mexutils.h.
static int uIsString (const mxArray * A, int L) [static]
Deprecated:
Array tests
Parameters:
A array to test.
L string length.
The array A satisfies the test if:
its storage class is CHAR;
it has two dimensions;
it has one row;
L < 0 or it has L columns.
Returns:
test result.
Definition at line 677 of file mexutils.h.
Referenced by uNextOption().
static int uIsVector (const mxArray * A, int N) [static]
Deprecated:
Array tests
Parameters:
A array to test.
N number of elements.
The array A satisfies the test if
It is a matrix (see uIsMatrix()).
It has a singleton dimension.
N < 0 or the other dimension is equal to N.
Returns:
test result.
Definition at line 521 of file mexutils.h.
References uIsMatrix().
static int uNextOption (mxArray const * args[], int nargs, uMexOption const * options, int * next, mxArray const ** optarg) [static]
Parameters:
args MEX argument array.
nargs MEX argument array length.
options List of option definitions.
next Pointer to the next option (in and out).
optarg Pointer to the option optional argument (out).
The function scans the MEX driver arguments array args of nargs elements for the next option starting at location next.
This argument is supposed to be the name of an option (case insensitive). The option is looked up in the option table options and decoded as the value uMexOption::val. Furthermore, if uMexOption::has_arg is true, the next entry in the array args is assumed to be argument of the option and stored in optarg. Finally, next is advanced to point to the next option.
Returns:
the code of the option, or -1 if the argument list is exhausted. In case of an error (e.g. unknown option) the function prints an error message and quits the MEX file.
Definition at line 825 of file mexutils.h.
References _uMexOption::has_arg, _uMexOption::name, uIsString(), uStrICmp(), and _uMexOption::val.
static int uStrICmp (const char * s1, const char * s2) [static]
Parameters:
s1 first string.
s2 second string.
Returns:
0 if the strings are equal, >0 if the first string is greater (in lexicographical order) and <0 otherwise.
Definition at line 786 of file mexutils.h.
Referenced by uNextOption().
VL_INLINE vl_bool vlmxIsMatrix (mxArray const * array, vl_index M, vl_index N)
Parameters:
array MATLAB array.
M number of rows (negative for any).
N number of columns (negative for any).
Returns:
VL_TRUE if the array is a matrix of the prescribed size.
See also:
Array tests
Definition at line 224 of file mexutils.h.
References VL_FALSE, and VL_TRUE.
Referenced by vlmxIsPlainMatrix().
VL_INLINE vl_bool vlmxIsOfClass (mxArray const * array, mxClassID classId)
Parameters:
array MATLAB array.
classId prescribed class of the array.
Returns:
VL_TRUE if the class is of the array is of the prescribed class.
See also:
Array tests
Definition at line 135 of file mexutils.h.
Referenced by vlmxIsPlainMatrix(), vlmxIsPlainScalar(), and vlmxIsPlainVector().
VL_INLINE vl_bool vlmxIsPlainMatrix (mxArray const * array, vl_index M, vl_index N)
Parameters:
array MATLAB array.
M number of rows (negative for any).
N number of columns (negative for any).
Returns:
VL_TRUE if the array is a plain matrix of the prescribed size.
See also:
Array tests
Definition at line 303 of file mexutils.h.
References vlmxIsMatrix(), vlmxIsOfClass(), and vlmxIsReal().
VL_INLINE vl_bool vlmxIsPlainScalar (mxArray const * array)
Parameters:
array MATLAB array.
Returns:
VL_TRUE if the array is plain scalar.
See also:
Array tests
Definition at line 266 of file mexutils.h.
References vlmxIsOfClass(), vlmxIsReal(), and vlmxIsScalar().
VL_INLINE vl_bool vlmxIsPlainVector (mxArray const * array, vl_index numElements)
Parameters:
array MATLAB array.
numElements number of elements (negative for any).
Returns:
VL_TRUE if the array is a plain vecotr of the prescribed size.
See also:
Array tests
Definition at line 284 of file mexutils.h.
References vlmxIsOfClass(), vlmxIsReal(), and vlmxIsVector().
VL_INLINE vl_bool vlmxIsReal (mxArray const * array)
Parameters:
array MATLAB array.
Returns:
VL_TRUE if the array is real.
See also:
Array tests
Definition at line 148 of file mexutils.h.
Referenced by vlmxIsPlainMatrix(), vlmxIsPlainScalar(), and vlmxIsPlainVector().
VL_INLINE vl_bool vlmxIsScalar (mxArray const * array)
Parameters:
array MATLAB array.
Returns:
VL_TRUE if the array is scalar.
See also:
Array tests
Definition at line 166 of file mexutils.h.
Referenced by vlmxIsPlainScalar().
VL_INLINE vl_bool vlmxIsVector (mxArray const * array, vl_index numElements)
Parameters:
array MATLAB array.
numElements number of elements (negative for any).
Returns:
VL_TRUE if the array is a vecotr of the prescribed size.
See also:
Array tests
Definition at line 180 of file mexutils.h.
References VL_FALSE, and VL_TRUE.
Referenced by vlmxIsPlainVector().
© 2005-09 Andrea Vedaldi and Brian Fulkerson